# Generated by Django 5.2.9 on 2025-12-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_is_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='image_data',
            field=models.TextField(blank=True, null=True, verbose_name='이미지 데이터 (Base64)'),
        ),
    ]
