# Generated by Django 5.2.9 on 2025-12-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ip_address',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
